name: widgetbook_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0
  point_design_system:
    path: ../poin-t-frontend/packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
